trigger:
  - master

pool:
  name: agent3

steps:
  - checkout: self
    displayName: 'Checkout Code'

  # Step to confirm Python installation (you've already installed it manually)
  - script: |
      echo "Python 3.9 is already installed"
    displayName: 'Confirm Python Installation'

  # Install Robot Framework and dependencies
  - script: |
      python -m venv venv
      call .\venv\Scripts\activate && pip install --upgrade pip
      pip install robotframework
      pip install robotframework-seleniumlibrary
      pip install robotframework-csvlibrary  
    displayName: 'Install Robot Framework & Dependencies'

  # Download ChromeDriver version 134.0.6998.35
  - script: |
      echo "Downloading ChromeDriver version 134.0.6998.35..."
      Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/134.0.6998.35/chromedriver_win32.zip" -OutFile "C:\chromedriver.zip"
      Expand-Archive -Path "C:\chromedriver.zip" -DestinationPath "C:\chromedriver"
      echo "ChromeDriver version 134.0.6998.35 downloaded and installed successfully"

      # Add ChromeDriver to PATH
      echo "Adding ChromeDriver to PATH"
      $env:Path += ";C:\chromedriver"
      echo "ChromeDriver path added"
    displayName: 'Download and Install ChromeDriver v134.0.6998.35'

  # List files in the test directory for debugging purposes
  - script: |
      echo "Checking test directory and files..."
      dir test
    displayName: 'Debug: List Test Files'

  # Run Robot Framework tests
  - script: |
      call .\venv\Scripts\activate && python -m robot --console verbose test/
    displayName: 'Run All Robot Framework Test Cases'
