trigger:
  - master
 
pool:
  name: agent3  
 
steps:
  - checkout: self
    displayName: 'Checkout Code'
 
  - script: |
      echo "Installing Python 3.9"
      choco install python --version 3.9 -y
    displayName: 'Install Python'
 
  - script: |
      python -m venv venv
      call .\venv\Scripts\activate && pip install --upgrade pip
      pip install robotframework
      pip install robotframework-seleniumlibrary
      pip install robotframework-csvlibrary  
    displayName: 'Install Robot Framework & Dependencies'
 
  - script: |
      choco install googlechrome chromedriver -y
    displayName: 'Install Chrome & ChromeDriver'
 
  - script: |
      echo "Checking test directory and files..."
      dir test
    displayName: 'Debug: List Test Files'
 
  - script: |
      call .\venv\Scripts\activate && python -m robot --console verbose test/
    displayName: 'Run All Robot Framework Test Cases'
 