trigger:
  - master

pool:
  name: mylocal

steps:
  - checkout: self
    displayName: 'Checkout Code'

  - script: |
      echo "Installing Python 3.9"
      curl -O https://www.python.org/ftp/python/3.9.0/python-3.9.0.exe
      python-3.9.0.exe /quiet InstallAllUsers=1 PrependPath=1
    displayName: 'Install Python 3.9'

  - script: |
      python -m venv venv
      call .\venv\Scripts\activate && pip install --upgrade pip
      pip install robotframework
      pip install robotframework-seleniumlibrary
      pip install robotframework-csvlibrary  
    displayName: 'Install Robot Framework & Dependencies'

  - script: |
      echo "Installing Chrome and ChromeDriver using winget"
      winget install --id Google.Chrome -e --source winget
      winget install --id Google.ChromeDriver -e --source winget
    displayName: 'Install Chrome & ChromeDriver using winget'

  - script: |
      echo "Checking test directory and files..."
      dir test
    displayName: 'Debug: List Test Files'

  - script: |
      call .\venv\Scripts\activate && python -m robot --console verbose test/
    displayName: 'Run All Robot Framework Test Cases'
